// src/RESTScaffold/Spinner.svelte
<script>
  let { size } = $props()
</script>

<div class="rs-loader" style={`width: ${size || "1.2em"}`}>
  <svg class="rs-circular" viewBox="25 25 50 50">
    <circle class="rs-path" cx="50" cy="50" r="20" fill="none" />
  </svg>
</div>

<style>
  .rs-loader {
    display: inline-block;
    position: relative;
  }

  .rs-loader:before {
    content: "";
    display: inline-block;
    padding-top: 100%;
  }

  .rs-loader .rs-circular {
    animation: rotate 2s linear infinite;
    height: 100%;
    transform-origin: center center;
    width: 100%;
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
  }

  .rs-loader .rs-circular .rs-path {
    stroke: light-dark(var(--rs-light-primary-bg), var(--rs-dark-primary-bg));
    animation: dash 1.5s ease-in-out infinite;
    stroke-linecap: round;
    stroke-width: 4;
    stroke-miterlimit: 10;
  }

  @keyframes rotate {
    100% {
      transform: rotate(360deg);
    }
  }

  @keyframes dash {
    0% {
      stroke-dasharray: 1, 200;
      stroke-dashoffset: 0;
    }
    50% {
      stroke-dasharray: 140, 200;
      stroke-dashoffset: -35px;
    }
    100% {
      stroke-dasharray: 140, 200;
      stroke-dashoffset: -124px;
    }
  }
</style>

// src/components/Spinner.vue
<script setup lang="ts">
const props = defineProps(["size"])
</script>

<template>
  <div class="loader" :style="{ width: props.size || '1.2em' }">
    <svg class="circular" viewBox="25 25 50 50">
      <circle class="path" cx="50" cy="50" r="20" fill="none" />
    </svg>
  </div>
</template>

<style scoped>
.loader {
  position: relative;
  margin: 0 auto;
}

.loader:before {
  content: "";
  display: block;
  padding-top: 100%;
}

.circular {
  animation: rotate 2s linear infinite;
  height: 100%;
  transform-origin: center center;
  width: 100%;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  margin: auto;
}

.path {
  stroke: blue;
  animation: dash 1.5s ease-in-out infinite;
  stroke-linecap: round;
  stroke-width: 4;
  stroke-miterlimit: 10;
}

@keyframes rotate {
  100% {
    transform: rotate(360deg);
  }
}

@keyframes dash {
  0% {
    stroke-dasharray: 1, 200;
    stroke-dashoffset: 0;
  }
  50% {
    stroke-dasharray: 140, 200;
    stroke-dashoffset: -35px;
  }
  100% {
    stroke-dasharray: 140, 200;
    stroke-dashoffset: -124px;
  }
}
</style>
